### ISSUE TITLE
silly q: what's the bot prefix?

### ISSUE THREAD

**Issue by Highfire1** [DV54321/FarmCord#9]
:c
![image](https://user-images.githubusercontent.com/45698812/125114576-fed8ae80-e09e-11eb-82d9-fc8b1a202003.png)

**Comment by amanogawa01** [comment]
What version are you using, the js or the C# one


Oh wait did you invite the bot?



I'm gonna be completely honest, I've been working on the bot for about 2 years now, and it's still nowhere near complete, mostly due to a lack of motivation and experience.

If I ever _do_ get the bot done it would be at least another couple years. 

Right now the bot is publicly invitable but it will be offline a lot as its still in development, so I don't suggest using it right now. 

That being said however if you do want to look at it, however barely running it is, the prefix should be `guava ` with a space after guava,
For example 
`guava help` will do the help command.

**Comment by Highfire1** [comment]
oh god posted this and completely forgot about it, coolio
